### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by zamrokk** [Tezsure/ctez#152]
All request finish on timeout

I can only login

then going to "my ovens" fails

`:1 Error while trying to use the following icon from the Manifest: https://ctez.app/ctez192.png (Download error or resource isn't a valid image)
query.js:317 TypeError: Cannot read properties of undefined (reading 'storage')
    at cfmm.ts:32:30
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at cfmm.ts:31:28
onError @ query.js:317
react_devtools_backend.js:3973 TypeError: Cannot read properties of undefined (reading 'storage')
    at ctez.ts:36:30
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at ctez.ts:35:28
overrideMethod @ react_devtools_backend.js:3973
onError @ query.js:317
p @ retryer.js:62
(anonymous) @ retryer.js:126
Promise.catch (async)
r @ retryer.js:110
(anonymous) @ retryer.js:143
react_devtools_backend.js:3973 TypeError: Cannot read properties of undefined (reading 'storage')
    at cfmm.ts:32:30
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at cfmm.ts:31:28`

**Comment by berndoostrum** [comment]
Is it persisting?
